
esphome:
  name: sauna-controller
  friendly_name: sauna-controller
  project:
    name: "darius-ger:sauna-controller"
    version: "0.1"
  preferences:
    flash_write_interval: 600s
  on_boot:
    priority: 200
    then:
      - climate.control:
          id: sauna_climate
          mode: 'OFF'
  # update OTA password
  #   - lambda: |-
  #       id(my_ota).set_auth_password("New OTA Password");

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# make log level selectable in HA
select:
  - platform: logger
    name: "Logger select"
    entity_category: CONFIG 


# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_encryption_key

ota:
  - platform: esphome
    id: my_ota
    password: !secret esp_OTA_password

wifi:
  ssid: !secret WiFi_IoT_SSID
  password: !secret WiFi_IoT_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sauna-Controller"
    password: "12345678"

captive_portal:



#Pinmapping
#GPIO 2   Door Reed contact 
#GPIO 5   Led Ligthing R
#GPIO 12  Led Ligthing G
#GPIO 13  Led Ligthing B
#GPIO 14  Led Ligthing W
#GPIO 16  Fan
#GPIO 27  Sauna oven L1
#GPIO 32  Sauna oven L2
#GPIO 33  Sauna oven L3
#GPIO 21  DHT22 (wall west)
#GPIO 22  DHT22 (Wall north) 
#GPIO 23  DHT22 (controll cabinet)
#GPIO 25  Dallas

#global variables
globals:
  - id: count_global_int
    type: int
    restore_value: no
    initial_value: '0'
  - id: count_global_door_int
    type: int
    restore_value: no
    initial_value: '0'

#the SSR relays for the sauna oven. 
output:
  - platform: template
    id: sauna_heater_output
    type: float
    write_action:
      - output.set_level:
          id: sauna_heater_output_L1
          level: !lambda 'return state;'
      - output.set_level:
          id: sauna_heater_output_L2
          level: !lambda 'return state;'
      - output.set_level:
          level: !lambda 'return state;'
          id: sauna_heater_output_L3
  - platform: slow_pwm
    pin: GPIO27
    id: sauna_heater_output_L1
    period: 60s    
  - platform: slow_pwm
    pin: GPIO32
    id: sauna_heater_output_L2
    period: 60s   
  - platform: slow_pwm
    pin: GPIO33
    id: sauna_heater_output_L3
    period: 60s 
#optional implementation using sigma_delta_output
# output:
#   - platform: sigma_delta_output
#     update_interval: 10s
#     id: sauna_heater_output

  #   # Output to a pin
  #   pin: GPIOXX

  # - platform: gpio
  #   pin: GPIOXX
  #   id: heater_relay

switch:
  - platform: template
    name:  ${friendly_name} PID Autotune
    turn_on_action:
      - climate.pid.autotune: sauna_climate
  -platform: gpio
    name: ${friendly_name} Lüftung
    id: sauna_fan
    icon: "mdi:fan"
    pin: GPIO16
      
     

one_wire:
  - platform: gpio
    pin: GPIO25


# Individual sensors
sensor:
  - platform: dht #a sensor in the control cabinet
    model: dht22    
    pin: GPIO23
    update_interval: 60s
    temperature:
      name: ${friendly_name} Steuerung Temperatur
      id: dht22_temperature_control_cabinet
    humidity:
      name: ${friendly_name} Steuerung Luftfeuchte
      id: dht22_humidity_control_cabinet
  - platform: dht #sensor in the wall north
    model: dht22    
    pin: GPIO22
    update_interval: 60s
    temperature:
      name: ${friendly_name} Wand Nord Temperatur
      id: dht22_temperature_wall_north
    humidity:
      name: ${friendly_name} Wand Nord Luftfeuchte
      id: dht22_humidity_wall_north
  - platform: template
      name: Tau Punkt ${friendly_name} Zwischenwand Nord
      id: dew_point_wall_north
      lambda: return (243.5*(log(id(dht22_humidity_wall_north).state/100)+((17.67*id(dht22_temperature_wall_north).state)/(243.5+id(dht22_temperature_wall_north).state)))/(17.67-log(id(dht22_humidity_wall_north).state/100)-((17.67*id(dht22_temperature_wall_north).state)/(243.5+id(dht22_temperature_wall_north).state))));
      unit_of_measurement: °C
      icon: 'mdi:thermometer-alert'
      update_interval: 60s
  - platform: dht #sensor in the wall west
    model: dht22    
    pin: GPIO21
    update_interval: 60s
    temperature:
      name: ${friendly_name} Wand West Temperatur
      id: dht22_temperature_wall_west
    humidity:
      name: ${friendly_name} Wand West Luftfeuchte
      id: dht22_humidity_wall_west
  - platform: dallas_temp
    address: 0x5391f6510a646128 #sensor on the ceeling near the oven
    name: ${friendly_name} Temperatur 
    id: sauna_temp
#   - platform: dallas
#     address: 0x07012042F262F228 #sensor below a bench
#     name: ${friendly_name} Temperatur unter der Bank
  - platform: template #gives the counter without a change back to HA (for debugging or so)
    name: ${user} Sauna Counter
    #unit_of_measurement: 'min'
    lambda: |-
      return id(count_global_int); 

  - platform: pid
    climate_id: sauna_climate
    name: ${friendly_name} PID Climate Result PROPORTIONAL
    type: PROPORTIONAL
  - platform: pid
    climate_id: sauna_climate
    name: ${friendly_name} PID Climate Result INTEGRAL 
    type: INTEGRAL 
  - platform: pid
    climate_id: sauna_climate
    name: ${friendly_name} PID Climate Result DERIVATIVE 
    type: DERIVATIVE 
  - platform: pid
    climate_id: sauna_climate
    name: ${friendly_name} PID Climate Result HEAT 
    id: generic_power
    type: HEAT 
  
  - platform: pid
    climate_id: sauna_climate
    name: ${friendly_name} aktuelle Leistung
    type: HEAT
    filters:
      - multiply: ${power_of_sauna_oven}
    unit_of_measurement: 'kW'
    id: power_of_sauna

  - platform: total_daily_energy
    name: ${friendly_name} Stromverbrauch täglich
    unit_of_measurement: 'kWh'
    power_id: power_of_sauna

  - platform: wifi_signal
    name: ${devicename} WiFi Signal Sensor
    update_interval: 60s
  
binary_sensor:
  - platform: gpio #reed contact at the door -> resets a timer not really needed
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      #inverted: True
    name: ${friendly_name} Tür
    device_class: "door"
    id: door_sensor
    filters:
      - delayed_on_off: 100ms
    on_release:
      then:
          - lambda: |-
              id(count_global_int)=0;

  - platform: template #switch on if sauna reaches target temperatur
    name: ${friendly_name} bereit
    device_class: "heat"
    id: sauna_ready

  - platform: status
    name: ${friendly_name} Status

# light:
#   # - platform: neopixelbus #fancy lamp for sauna
#   #   method: ESP8266_UART1
#   #   variant: WS2812
#   #   type: GRB
#   #   pin: D4
#   #   num_leds: 133
#   #   name: ${user} Sauna Licht
#   #   id: sauna_licht
#   #   effects:
#   #     - random:
#   #     - strobe:
#   #     - addressable_rainbow:
#   #     - addressable_twinkle:
#   #     - addressable_color_wipe:
#   #     - addressable_scan:
#   #     - addressable_twinkle:
#   #         name: Twinkle Effect With Custom Values
#   #         twinkle_probability: 15%
#   #         progress_interval: 4ms
#   #     - addressable_random_twinkle:
#   #     - addressable_fireworks:
#   #     - addressable_fireworks:
#   #         name: Fireworks Effect With Custom Values
#   #         update_interval: 32ms
#   #         spark_probability: 40%
#   #         use_random_color: false
#   #         fade_out_rate: 120

#every minute a event is fired, to switch the Sauna off after 90min without opening the door
#If the door is open for more than 5min switch off the sauna
time:
  - platform: sntp
    # ...
    on_time:
      # Every minute
      - seconds: 0
        minutes: /1
        then:
          - lambda: |-
              if (id(sauna_climate).mode==climate::CLIMATE_MODE_OFF) {
                id(count_global_int)=0;
                id(sauna_ready).publish_state(false);
              }else{
                id(count_global_int)++;
                if (!id(door_sensor).state) {
                  id(count_global_door_int)=0;
                }else{
                  //If the door is open for more than 5min switch off the sauna
                  id(count_global_door_int)++;
                  if (id(count_global_door_int)>5){
                    auto call = id(sauna_climate).make_call();
                    call.set_mode("OFF");
                    call.perform();
                  }
                }
                if (id(sauna_climate).current_temperature > id(sauna_climate).target_temperature){
                  //reset the timer after reaching the target temperature
                  if (id(sauna_ready).state==false){
                    id(count_global_int)=0;
                  }
                  id(sauna_ready).publish_state(true);
                }
              }
              if (id(count_global_int) > 90){
                auto call = id(sauna_climate).make_call();
                call.set_mode("OFF");
                call.perform();
              }
#                

climate:
  - platform: pid #parameters suitable for my sauna with 7kw oven and about 1.7x1.6x2.2m^3
    id: sauna_climate
    name: ${friendly_name} Steuerung
    sensor: sauna_temp
    default_target_temperature: 30°C
    #hysteresis: 1 °C
    #default_target_temperature_high: 60 °C
    heat_output: sauna_heater_output
    control_parameters:
      kp: 0.17181
      ki: 0.00015
      kd: 75.09859

    visual:
      min_temperature: 10 °C
      max_temperature: 100 °C
      temperature_step: 1 °C

